name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Create Release With Asset
        uses: Hs1r1us/Release-AIO@v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          asset_files: './release.zip'
      - name: Duplicate Release With Asset to public_Repo
        uses: Hs1r1us/Release-AIO@v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # You need a new token to access the target Repository
        with:
          tag_name: 'inherit' # Must use 'inherit' to get the latest release
          body: 'release zip' # Will be added in the new release
          repo: 'yang10560/tampermonkey-userscript' # The format is like owner/repo
          asset_files: './release.zip' # Will be added in the new release